import React from 'react';
import { Routes, Route, Navigate } from 'react-router-dom';
import LandingPage from './pages/LandingPage';
import Dashboard from './pages/Dashboard';
import SuperAdminDashboard from './pages/SuperAdminDashboard';
import QuizPage from './pages/QuizPage';
import Profile from './pages/Profile';
import Leaderboard from './pages/Leaderboard';
import AdminPanel from './pages/AdminPanel';
import CodeLab from './pages/CodeLab';
import AIAssistant from './pages/AIAssistant';
import TheoryVault from './pages/TheoryVault';
import Cybersecurity from './pages/Cybersecurity';
import Analytics from './pages/Analytics';
import UserManagement from './pages/admin/UserManagement';
import LoginPage from './auth/LoginPage';
import RegisterPage from './auth/RegisterPage';
import ForgotPassword from './auth/ForgotPassword';
import ProtectedRoute from './auth/ProtectedRoute';
import { AuthProvider } from './context/AuthContext';
import { db } from './services/firebase';
import { collection, getDocs, addDoc } from 'firebase/firestore';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const INITIAL_QUESTIONS = [
  // ─── JavaScript ────────────────────────────────
  { question: "What is the output of typeof null?", options: ["'object'", "'null'", "'undefined'", "'number'"], correct: 0, difficulty: "medium", category: "JavaScript", explanation: "typeof null returns 'object' — a well-known JS quirk." },
  { question: "Which keyword is used to define a constant in ES6?", options: ["var", "let", "const", "def"], correct: 2, difficulty: "easy", category: "JavaScript", explanation: "const declares a block-scoped, read-only variable." },
  { question: "What is hoisting in JavaScript?", options: ["Moving declarations to top", "Lifting errors", "A way to loop", "Memory cleanup"], correct: 0, difficulty: "hard", category: "JavaScript", explanation: "Hoisting moves all declarations to the top of their scope before execution." },
  { question: "What does '===' check?", options: ["Value only", "Value and type", "Reference only", "Nothing"], correct: 1, difficulty: "easy", category: "JavaScript", explanation: "=== checks both value and type (strict equality)." },
  { question: "Which method adds an element to the end of an array?", options: ["unshift()", "push()", "pop()", "shift()"], correct: 1, difficulty: "easy", category: "JavaScript", explanation: "push() appends one or more elements to the end of an array." },
  { question: "What is a closure?", options: ["A loop construct", "A function with access to its outer scope", "A closed browser tab", "A type of variable"], correct: 1, difficulty: "medium", category: "JavaScript", explanation: "A closure is a function that retains access to variables from its enclosing scope." },
  { question: "What is the output of: console.log(0.1 + 0.2 === 0.3)?", options: ["true", "false", "undefined", "TypeError"], correct: 1, difficulty: "medium", category: "JavaScript", explanation: "Floating-point precision issue — 0.1 + 0.2 equals 0.30000000000000004." },
  { question: "Which symbol is used for template literals?", options: ["Single quotes ''", "Double quotes \"\"", "Backticks ` `", "Parentheses ()"], correct: 2, difficulty: "easy", category: "JavaScript", explanation: "Template literals use backticks and support ${} interpolation." },
  { question: "What does Array.prototype.reduce() return?", options: ["A new array", "A single value", "undefined", "A boolean"], correct: 1, difficulty: "medium", category: "JavaScript", explanation: "reduce() accumulates array elements into a single output value." },
  { question: "What is the purpose of 'use strict'?", options: ["Enables ES6 features", "Enables strict mode catching common mistakes", "Makes code run faster", "Disables console.log"], correct: 1, difficulty: "medium", category: "JavaScript", explanation: "Strict mode helps catch unsafe actions and ambiguous behavior." },
  { question: "What is event bubbling?", options: ["Events going from parent to child", "Events going from child to parent", "Events being canceled", "Events firing twice"], correct: 1, difficulty: "medium", category: "JavaScript", explanation: "Event bubbling means events propagate from the innermost target up to the root." },
  { question: "Which method creates a new array with filtered elements?", options: ["map()", "forEach()", "filter()", "reduce()"], correct: 2, difficulty: "easy", category: "JavaScript", explanation: "filter() returns a new array with elements that pass the test function." },
  { question: "What is a Promise?", options: ["A variable type", "An object representing eventual completion of an async operation", "A loop", "A function"], correct: 1, difficulty: "medium", category: "JavaScript", explanation: "A Promise represents a value that may be available now, later, or never." },
  { question: "What does the 'async' keyword do?", options: ["Makes a function synchronous", "Makes a function return a Promise", "Deletes the function", "Makes a variable constant"], correct: 1, difficulty: "medium", category: "JavaScript", explanation: "async functions always return a Promise and allow use of await inside." },
  { question: "What is the output of typeof undefined?", options: ["'object'", "'null'", "'undefined'", "'boolean'"], correct: 2, difficulty: "easy", category: "JavaScript", explanation: "typeof undefined correctly returns the string 'undefined'." },
  { question: "Which method is used to convert a JSON string to an object?", options: ["JSON.stringify()", "JSON.parse()", "JSON.toObject()", "JSON.convert()"], correct: 1, difficulty: "easy", category: "JavaScript", explanation: "JSON.parse() deserializes a JSON string into a JavaScript object." },
  { question: "What is the event loop?", options: ["A type of for-loop", "A mechanism that handles async callbacks", "A recursion pattern", "A DOM method"], correct: 1, difficulty: "hard", category: "JavaScript", explanation: "The event loop continuously checks the call stack and task queue to execute callbacks." },
  { question: "What is destructuring assignment?", options: ["Breaking objects", "Extracting values from arrays/objects into variables", "Deleting properties", "Merging arrays"], correct: 1, difficulty: "easy", category: "JavaScript", explanation: "Destructuring lets you unpack values from arrays or properties from objects into distinct variables." },
  { question: "What is the spread operator?", options: ["...", "**", "&&", "=>"], correct: 0, difficulty: "easy", category: "JavaScript", explanation: "The spread operator (...) expands an iterable into individual elements." },
  { question: "Which method finds the first element that matches a condition?", options: ["find()", "filter()", "indexOf()", "search()"], correct: 0, difficulty: "medium", category: "JavaScript", explanation: "find() returns the first element that satisfies the provided testing function." },

  // ─── HTML ──────────────────────────────────────
  { question: "What does HTML stand for?", options: ["Hyper Text Markup Language", "High Tech Modern Language", "Home Tool Markup Language", "Hyperlink Text Mode Language"], correct: 0, difficulty: "easy", category: "HTML", explanation: "HTML stands for HyperText Markup Language." },
  { question: "Which tag is used for the largest heading?", options: ["<heading>", "<h6>", "<h1>", "<head>"], correct: 2, difficulty: "easy", category: "HTML", explanation: "<h1> defines the largest and most important heading." },
  { question: "Which attribute is used to specify an image source?", options: ["href", "link", "src", "img"], correct: 2, difficulty: "easy", category: "HTML", explanation: "The src attribute specifies the path to the image." },
  { question: "What is the correct HTML for creating a hyperlink?", options: ["<link>url</link>", "<a href='url'>link</a>", "<href>url</href>", "<url>link</url>"], correct: 1, difficulty: "easy", category: "HTML", explanation: "The <a> tag with href attribute creates hyperlinks." },
  { question: "Which tag is used for an unordered list?", options: ["<ol>", "<li>", "<ul>", "<list>"], correct: 2, difficulty: "easy", category: "HTML", explanation: "<ul> creates an unordered (bulleted) list." },
  { question: "What is the correct way to add a comment in HTML?", options: ["// comment", "/* comment */", "<!-- comment -->", "# comment"], correct: 2, difficulty: "easy", category: "HTML", explanation: "HTML comments are written between <!-- and -->." },
  { question: "Which meta tag controls viewport behavior on mobile?", options: ["<meta charset>", "<meta name='viewport'>", "<meta name='description'>", "<meta name='author'>"], correct: 1, difficulty: "medium", category: "HTML", explanation: "The viewport meta tag controls layout and scaling on mobile devices." },
  { question: "Which element represents the main content of a document?", options: ["<div>", "<section>", "<main>", "<body>"], correct: 2, difficulty: "medium", category: "HTML", explanation: "<main> represents the dominant content of the <body>." },
  { question: "What is the purpose of the <form> tag?", options: ["Display data", "Create input forms for user data", "Style content", "Link pages"], correct: 1, difficulty: "easy", category: "HTML", explanation: "The <form> element contains interactive controls for submitting information." },
  { question: "Which attribute makes an input field required?", options: ["mandatory", "required", "validate", "necessary"], correct: 1, difficulty: "easy", category: "HTML", explanation: "The required attribute specifies that an input field must be filled before submitting." },
  { question: "What does the <canvas> element do?", options: ["Displays vector graphics", "Provides a drawing surface via JavaScript", "Creates 3D models", "Embeds PDF files"], correct: 1, difficulty: "medium", category: "HTML", explanation: "<canvas> provides a resolution-dependent bitmap rendering surface for drawing with JS." },
  { question: "Which tag is used for a navigation section?", options: ["<nav>", "<menu>", "<navigate>", "<links>"], correct: 0, difficulty: "easy", category: "HTML", explanation: "<nav> represents a section with navigation links." },
  { question: "What is semantic HTML?", options: ["HTML with animations", "Using tags that describe meaning", "HTML with CSS", "Compressed HTML"], correct: 1, difficulty: "medium", category: "HTML", explanation: "Semantic HTML uses meaningful tags like <header>, <article>, <footer> instead of generic <div>." },
  { question: "Which input type creates a date picker?", options: ["text", "date", "calendar", "time"], correct: 1, difficulty: "easy", category: "HTML", explanation: "input type='date' provides a native date picker in modern browsers." },
  { question: "What is the purpose of the alt attribute on images?", options: ["Sets image size", "Provides alternative text for accessibility", "Adds a caption", "Defines image format"], correct: 1, difficulty: "easy", category: "HTML", explanation: "alt text describes the image for screen readers and when the image fails to load." },

  // ─── CSS ───────────────────────────────────────
  { question: "What does CSS stand for?", options: ["Computer Style Sheets", "Cascading Style Sheets", "Creative Style System", "Colorful Style Sheets"], correct: 1, difficulty: "easy", category: "CSS", explanation: "CSS stands for Cascading Style Sheets." },
  { question: "Which property changes text color?", options: ["font-color", "text-color", "color", "foreground"], correct: 2, difficulty: "easy", category: "CSS", explanation: "The color property sets the text color of an element." },
  { question: "How do you select an element with id 'main'?", options: [".main", "#main", "main", "*main"], correct: 1, difficulty: "easy", category: "CSS", explanation: "The # selector targets elements by their ID." },
  { question: "Which property controls text size?", options: ["text-size", "font-size", "text-style", "font-style"], correct: 1, difficulty: "easy", category: "CSS", explanation: "font-size sets the size of the font." },
  { question: "What is the CSS box model?", options: ["A 3D rendering technique", "Content + Padding + Border + Margin", "A JavaScript object", "A layout algorithm"], correct: 1, difficulty: "medium", category: "CSS", explanation: "The box model describes the rectangular boxes generated for elements: content, padding, border, margin." },
  { question: "Which property creates space inside an element's border?", options: ["margin", "padding", "border-spacing", "gap"], correct: 1, difficulty: "easy", category: "CSS", explanation: "Padding creates space between the content and the border." },
  { question: "How do you make text bold in CSS?", options: ["font-weight: bold", "text-weight: bold", "font-style: bold", "text-bold: true"], correct: 0, difficulty: "easy", category: "CSS", explanation: "font-weight: bold makes text bold." },
  { question: "What does display: flex do?", options: ["Makes text flexible", "Creates a flexbox container", "Hides the element", "Adds animation"], correct: 1, difficulty: "medium", category: "CSS", explanation: "display: flex enables flexbox layout for the element's children." },
  { question: "Which property adds shadow to text?", options: ["text-shadow", "box-shadow", "font-shadow", "shadow"], correct: 0, difficulty: "medium", category: "CSS", explanation: "text-shadow adds shadow effect to text." },
  { question: "What is CSS specificity?", options: ["How fast CSS loads", "The priority order of CSS rules", "Browser compatibility", "File size of stylesheets"], correct: 1, difficulty: "medium", category: "CSS", explanation: "Specificity determines which CSS rule is applied when multiple rules match the same element." },
  { question: "Which value of position keeps an element in the normal flow?", options: ["fixed", "absolute", "static", "sticky"], correct: 2, difficulty: "medium", category: "CSS", explanation: "static is the default — element follows normal document flow." },
  { question: "How do you center a block element horizontally?", options: ["margin: 0 auto", "text-align: center", "display: center", "float: center"], correct: 0, difficulty: "medium", category: "CSS", explanation: "margin: 0 auto centers a block element within its parent." },
  { question: "Which property creates rounded corners?", options: ["border-radius", "corner-radius", "rounded", "border-style"], correct: 0, difficulty: "easy", category: "CSS", explanation: "border-radius defines the radius of the element's corners." },
  { question: "What does z-index control?", options: ["Text size", "Stacking order of overlapping elements", "Animation speed", "Color depth"], correct: 1, difficulty: "medium", category: "CSS", explanation: "z-index controls the vertical stacking order of positioned elements." },
  { question: "Which CSS unit is relative to the parent element's font size?", options: ["px", "em", "vh", "pt"], correct: 1, difficulty: "medium", category: "CSS", explanation: "em is relative to the font size of the parent element." },

  // ─── React ─────────────────────────────────────
  { question: "What is React?", options: ["A database", "A JavaScript library for building UIs", "A CSS framework", "A server language"], correct: 1, difficulty: "easy", category: "React", explanation: "React is a JavaScript library for building user interfaces." },
  { question: "What is JSX?", options: ["A new programming language", "JavaScript XML — syntax extension for JS", "A CSS preprocessor", "A testing tool"], correct: 1, difficulty: "easy", category: "React", explanation: "JSX lets you write HTML-like syntax inside JavaScript." },
  { question: "What hook is used for side effects?", options: ["useState", "useEffect", "useContext", "useReducer"], correct: 1, difficulty: "easy", category: "React", explanation: "useEffect handles side effects like data fetching and subscriptions." },
  { question: "What does useState return?", options: ["Just the value", "A state variable and a setter function", "An object", "A Promise"], correct: 1, difficulty: "easy", category: "React", explanation: "useState returns [state, setState] — the current value and a function to update it." },
  { question: "What is a prop in React?", options: ["A local variable", "Data passed from parent to child component", "A global state", "A CSS property"], correct: 1, difficulty: "easy", category: "React", explanation: "Props are read-only data passed from a parent component to a child." },
  { question: "What is the virtual DOM?", options: ["The real DOM", "A lightweight copy of the real DOM", "A browser API", "A testing framework"], correct: 1, difficulty: "medium", category: "React", explanation: "React keeps a virtual copy of the DOM to minimize expensive real DOM operations." },
  { question: "When does useEffect run by default?", options: ["Before every render", "After every render", "Only once on mount", "Never"], correct: 1, difficulty: "medium", category: "React", explanation: "By default, useEffect runs after every completed render." },
  { question: "What is the key prop used for?", options: ["Styling elements", "Helping React identify list items", "Setting state", "Fetching data"], correct: 1, difficulty: "medium", category: "React", explanation: "Keys help React identify which items have changed, been added, or removed in lists." },
  { question: "What is prop drilling?", options: ["Passing props deeply through many components", "Deleting props", "Using TypeScript", "Memoizing props"], correct: 0, difficulty: "medium", category: "React", explanation: "Prop drilling is passing data through many intermediate components to reach a deeply nested child." },
  { question: "What is React Context used for?", options: ["Styling", "Sharing state globally without prop drilling", "Routing", "Form validation"], correct: 1, difficulty: "medium", category: "React", explanation: "Context provides a way to share values between components without explicitly passing props." },
  { question: "What does useRef return?", options: ["A DOM element directly", "A mutable ref object with .current", "A state variable", "A Promise"], correct: 1, difficulty: "medium", category: "React", explanation: "useRef returns { current: initialValue } — a persistent mutable object across renders." },
  { question: "Which hook replaces Redux for simple state?", options: ["useState", "useReducer", "useEffect", "useMemo"], correct: 1, difficulty: "medium", category: "React", explanation: "useReducer manages complex state logic with a reducer function, similar to Redux." },
  { question: "What does useMemo do?", options: ["Memorizes component names", "Caches expensive computations between renders", "Creates memo files", "Stores form data"], correct: 1, difficulty: "hard", category: "React", explanation: "useMemo returns a memoized value, recalculating only when dependencies change." },
  { question: "What is React.memo used for?", options: ["Adding comments", "Preventing unnecessary re-renders of a component", "Memoizing events", "Saving data to localStorage"], correct: 1, difficulty: "hard", category: "React", explanation: "React.memo skips re-rendering a component if its props haven't changed." },

  // ─── Cybersecurity ─────────────────────────────
  { question: "What is XSS?", options: ["Cross-Site Scripting", "Extra Secure System", "External Style Sheet", "Extra Safe Storage"], correct: 0, difficulty: "easy", category: "Cybersecurity", explanation: "XSS (Cross-Site Scripting) injects malicious scripts into trusted websites." },
  { question: "What is SQL injection?", options: ["Adding SQL to a database", "Inserting malicious SQL code into queries", "Optimizing SQL queries", "Creating SQL tables"], correct: 1, difficulty: "easy", category: "Cybersecurity", explanation: "SQL injection inserts malicious SQL statements into input fields to manipulate the database." },
  { question: "What does HTTPS encrypt?", options: ["Only passwords", "Data in transit between client and server", "Files on disk", "CPU instructions"], correct: 1, difficulty: "easy", category: "Cybersecurity", explanation: "HTTPS encrypts all data transmitted between the browser and the server." },
  { question: "What is a firewall?", options: ["A physical wall", "A network security system monitoring traffic", "A type of virus", "An antivirus software"], correct: 1, difficulty: "easy", category: "Cybersecurity", explanation: "A firewall monitors and controls incoming and outgoing network traffic based on security rules." },
  { question: "What is phishing?", options: ["Fishing for data in a lake", "A social engineering attack tricking users into revealing info", "A type of malware", "A password manager"], correct: 1, difficulty: "easy", category: "Cybersecurity", explanation: "Phishing tricks users into providing sensitive data by posing as a trustworthy entity." },
  { question: "What makes a strong password?", options: ["Your birthday", "Short and simple", "At least 12 characters with mixed types", "A dictionary word"], correct: 2, difficulty: "easy", category: "Cybersecurity", explanation: "Strong passwords use 12+ characters with uppercase, lowercase, numbers, and symbols." },
  { question: "What is two-factor authentication (2FA)?", options: ["Using two passwords", "Requiring two forms of verification to log in", "Logging in twice", "Having two accounts"], correct: 1, difficulty: "easy", category: "Cybersecurity", explanation: "2FA adds an extra layer by requiring a second form of identification beyond just a password." },
  { question: "What is CSRF?", options: ["Cross-Site Request Forgery", "Computer Security Research Foundation", "Certified Secure File Registry", "Cross System File Reader"], correct: 0, difficulty: "medium", category: "Cybersecurity", explanation: "CSRF tricks authenticated users into submitting unintended requests to a web application." },
  { question: "What is the purpose of input sanitization?", options: ["Making inputs pretty", "Removing or encoding dangerous characters from user input", "Encrypting data", " compressing data"], correct: 1, difficulty: "medium", category: "Cybersecurity", explanation: "Input sanitization prevents injection attacks by cleaning user-provided data." },
  { question: "What is a man-in-the-middle attack?", options: ["A physical attack", "Intercepting communication between two parties", "Attacking a server directly", "Using a VPN"], correct: 1, difficulty: "medium", category: "Cybersecurity", explanation: "An attacker secretly intercepts and possibly alters communication between two parties." },
  { question: "What is CORS?", options: ["Cross-Origin Resource Sharing — controls cross-domain requests", "A type of encryption", "A password hashing algorithm", "A DNS service"], correct: 0, difficulty: "medium", category: "Cybersecurity", explanation: "CORS is a security mechanism that allows or restricts resource requests from different origins." },
  { question: "What does a salt do in password hashing?", options: ["Makes passwords longer", "Adds random data before hashing to prevent rainbow tables", "Encrypts the password", "Stores the password in plain text"], correct: 1, difficulty: "medium", category: "Cybersecurity", explanation: "Salting adds unique random data to each password before hashing, defeating precomputed attacks." },
  { question: "What is zero trust security?", options: ["Trusting no one by default", "No security at all", "Trusting everyone on the network", "A single password system"], correct: 0, difficulty: "medium", category: "Cybersecurity", explanation: "Zero trust means no user or device is trusted by default, even inside the network perimeter." },
  { question: "What is the principle of least privilege?", options: ["Giving all users admin access", "Granting only the minimum permissions needed", "Locking all accounts", "Using the weakest password"], correct: 1, difficulty: "medium", category: "Cybersecurity", explanation: "Least privilege means giving users only the access they need to perform their job — nothing more." },
  { question: "What is OWASP?", options: ["A web browser", "Open Web Application Security Project — a security standard", "A programming language", "A firewall brand"], correct: 1, difficulty: "medium", category: "Cybersecurity", explanation: "OWASP is a nonprofit foundation working to improve software security through standards and tools." },
  // ─── JavaScript (additional) ────────────────────
  { question: "What does Array.prototype.flat() do?", options: ["Removes duplicates", "Flattens nested arrays by one level", "Sorts the array", "Reverses the array"], correct: 1, difficulty: "easy", category: "JavaScript", explanation: "flat() creates a new array with sub-array elements concatenated up to the specified depth." },
  { question: "What is the output of: console.log(1 + '2' + 3)?", options: ["6", "'123'", "'33'", "NaN"], correct: 1, difficulty: "easy", category: "JavaScript", explanation: "Number 1 is coerced to string, then concatenated with '2' and '3'." },
  { question: "Which method removes the last element from an array?", options: ["shift()", "pop()", "splice()", "slice()"], correct: 1, difficulty: "easy", category: "JavaScript", explanation: "pop() removes and returns the last element of an array." },
  { question: "What is the output of: typeof NaN?", options: ["'NaN'", "'number'", "'undefined'", "'object'"], correct: 1, difficulty: "easy", category: "JavaScript", explanation: "typeof NaN returns 'number' — NaN is technically a numeric value." },
  { question: "What does Object.keys() return?", options: ["Array of values", "Array of property names", "Array of entries", "The object itself"], correct: 1, difficulty: "easy", category: "JavaScript", explanation: "Object.keys() returns an array of a given object's own enumerable property names." },
  { question: "How do you create a regular expression in JS?", options: ["/pattern/", "new RegExp[]", "regex(pattern)", "re(pattern)"], correct: 0, difficulty: "easy", category: "JavaScript", explanation: "Regular expressions are created using literal syntax /pattern/ or new RegExp()." },
  { question: "What does Array.prototype.find() return?", options: ["An array", "The first matching element", "The index", "A boolean"], correct: 1, difficulty: "easy", category: "JavaScript", explanation: "find() returns the first element that satisfies the testing function, or undefined." },
  { question: "What is the output of: console.log([] == false)?", options: ["true", "false", "TypeError", "undefined"], correct: 0, difficulty: "easy", category: "JavaScript", explanation: "An empty array is coerced to 0, and 0 == false is true." },
  { question: "What does 'this' refer to in an arrow function?", options: ["The calling object", "The enclosing lexical scope", "undefined", "The global object"], correct: 1, difficulty: "medium", category: "JavaScript", explanation: "Arrow functions don't have their own 'this' — they inherit from the surrounding scope." },
  { question: "What is the difference between let and var?", options: ["No difference", "let is block-scoped, var is function-scoped", "var is newer", "let is global"], correct: 1, difficulty: "medium", category: "JavaScript", explanation: "let respects block scope (if, for, while), while var is scoped to the nearest function." },
  { question: "What does Promise.all() do?", options: ["Runs promises sequentially", "Resolves when ALL promises resolve, rejects if any reject", "Resolves with the first promise", "Merges promise outputs"], correct: 1, difficulty: "medium", category: "JavaScript", explanation: "Promise.all() takes an iterable of promises and returns a single promise that resolves when all input promises resolve." },
  { question: "What is the output of: console.log(typeof function() {})?", options: ["'function'", "'object'", "'undefined'", "'method'"], correct: 0, difficulty: "medium", category: "JavaScript", explanation: "typeof a function returns 'function' in JavaScript." },
  { question: "What does Array.prototype.some() check?", options: ["All elements pass", "At least one element passes", "No elements pass", "Exactly one element passes"], correct: 1, difficulty: "medium", category: "JavaScript", explanation: "some() tests whether at least one element passes the provided function." },
  { question: "What is the purpose of JSON.stringify()?", options: ["Parse JSON", "Convert JS object to JSON string", "Validate JSON", "Compress data"], correct: 1, difficulty: "medium", category: "JavaScript", explanation: "JSON.stringify() serializes a JavaScript object or value to a JSON string." },
  { question: "What does the !important rule do in CSS (via JS)?", options: ["Makes code faster", "Overrides normal specificity", "Deletes the rule", "Duplicates the element"], correct: 1, difficulty: "medium", category: "JavaScript", explanation: "!important overrides all other declarations regardless of specificity." },
  { question: "What is a WeakMap?", options: ["A map with weak keys", "A Map that only accepts objects as keys and allows garbage collection", "A deprecated Map", "A Map with null values"], correct: 1, difficulty: "medium", category: "JavaScript", explanation: "WeakMap holds weak references to its keys, allowing garbage collection of key objects." },
  { question: "What is the output of: console.log(0 === -0)?", options: ["false", "true", "TypeError", "undefined"], correct: 1, difficulty: "medium", category: "JavaScript", explanation: "0 and -0 are strictly equal in JavaScript." },
  { question: "What does setTimeout() return?", options: ["The result of the callback", "A timer ID (number)", "undefined", "A Promise"], correct: 1, difficulty: "medium", category: "JavaScript", explanation: "setTimeout returns a numeric ID that can be used with clearTimeout()." },
  { question: "What is the spread operator used for in function arguments?", options: ["Merging objects", "Expanding an array as individual arguments", "Creating arrays", "Deleting elements"], correct: 1, difficulty: "medium", category: "JavaScript", explanation: "The spread operator ... can expand an array into individual function arguments." },
  { question: "What does Object.freeze() do?", options: ["Deletes the object", "Makes the object immutable", "Compresses the object", "Clones the object"], correct: 1, difficulty: "hard", category: "JavaScript", explanation: "Object.freeze() prevents modifications to existing properties and their values." },
  { question: "What is a generator's return value?", options: ["The last yield value", "An Iterator object", "undefined", "A resolved Promise"], correct: 1, difficulty: "hard", category: "JavaScript", explanation: "A generator function returns an iterator object with next(), return(), and throw() methods." },
  { question: "What is the difference between == and ===?", options: ["No difference", "== checks value only, === checks value and type", "=== is faster", "== checks reference"], correct: 1, difficulty: "hard", category: "JavaScript", explanation: "== performs type coercion before comparison, === does not (strict equality)." },
  { question: "What is tail call optimization?", options: ["Optimizing loops", "Optimizing the last function call to avoid stack overflow", "Optimizing Promises", "Optimizing event listeners"], correct: 1, difficulty: "hard", category: "JavaScript", explanation: "TCO allows the JS engine to reuse stack frames when the last action is a function call." },
  { question: "What does Reflect API provide?", options: ["Reflection of light", "Methods for interceptable JavaScript operations", "A debugging tool", "A networking API"], correct: 1, difficulty: "hard", category: "JavaScript", explanation: "Reflect provides methods for interceptable operations like property access, assignment, and function calls." },
  { question: "What is the temporal dead zone?", options: ["A movie reference", "The period where let/const variables exist but cannot be accessed", "A memory leak", "An async timing issue"], correct: 1, difficulty: "hard", category: "JavaScript", explanation: "TDZ is the zone between block entry and variable declaration where let/const variables throw ReferenceError." },
  { question: "What is the difference between call and apply?", options: ["No difference", "call takes arguments individually, apply takes an array", "apply is older", "call is for classes only"], correct: 1, difficulty: "hard", category: "JavaScript", explanation: "call() passes arguments one by one, apply() passes them as an array." },
  { question: "What does the 'with' statement do?", options: ["Adds a property", "Creates a new scope with an object as the scope chain", "Loops through properties", "Imports a module"], correct: 1, difficulty: "hard", category: "JavaScript", explanation: "with extends the scope chain for a block with properties of the given object (disallowed in strict mode)." },
  { question: "What is the output of: 0.1 + 0.2?", options: ["0.3", "0.30000000000000004", "0.2999999999999999", "0.4"], correct: 1, difficulty: "hard", category: "JavaScript", explanation: "Due to IEEE 754 floating-point precision, 0.1 + 0.2 equals 0.30000000000000004." },
  { question: "What is the difference between Symbol.for() and Symbol()?", options: ["No difference", "Symbol.for() creates/reuses global symbols, Symbol() creates unique ones", "Symbol.for() is deprecated", "Symbol() is global"], correct: 1, difficulty: "hard", category: "JavaScript", explanation: "Symbol.for() creates a symbol in a global symbol registry, reusing existing ones with the same key." },
  { question: "What is structuredClone() used for?", options: ["Shallow copy", "Deep copy of objects including circular references", "Cloning DOM nodes", "Copying primitives"], correct: 1, difficulty: "hard", category: "JavaScript", explanation: "structuredClone() creates a deep copy of a value, supporting circular references and complex objects." },

  // ─── HTML (additional) ──────────────────────────
  { question: "Which tag defines a table row?", options: ["<td>", "<th>", "<tr>", "<table>"], correct: 2, difficulty: "easy", category: "HTML", explanation: "<tr> defines a row of cells in a table." },
  { question: "Which attribute specifies inline CSS?", options: ["class", "style", "css", "styles"], correct: 1, difficulty: "easy", category: "HTML", explanation: "The style attribute adds inline CSS directly to an element." },
  { question: "What is the correct tag for a line break?", options: ["<break>", "<lb>", "<br>", "<newline>"], correct: 2, difficulty: "easy", category: "HTML", explanation: "<br> inserts a single line break." },
  { question: "Which tag is used for emphasis (italic)?", options: ["<bold>", "<i>", "<em>", "<italic>"], correct: 2, difficulty: "easy", category: "HTML", explanation: "<em> marks text as emphasized, typically rendered in italic." },
  { question: "What does the <video> tag do?", options: ["Plays audio only", "Embeds a video player", "Creates a video file", "Records video"], correct: 1, difficulty: "easy", category: "HTML", explanation: "<video> embeds a media player for video content." },
  { question: "Which input type creates a checkbox?", options: ["radio", "check", "checkbox", "toggle"], correct: 2, difficulty: "easy", category: "HTML", explanation: "input type='checkbox' creates a toggleable checkbox." },
  { question: "What tag defines a description list?", options: ["<dl>", "<dd>", "<dt>", "<list>"], correct: 0, difficulty: "easy", category: "HTML", explanation: "<dl> defines a description list, with <dt> terms and <dd> descriptions." },
  { question: "Which attribute opens a link in a new tab?", options: ["target='_self'", "target='_blank'", "new='true'", "open='new'"], correct: 1, difficulty: "easy", category: "HTML", explanation: "target='_blank' opens the linked document in a new tab or window." },
  { question: "What does the <abbr> tag define?", options: ["An abbreviation", "An abstract", "An anchor", "An article"], correct: 0, difficulty: "easy", category: "HTML", explanation: "<abbr> represents an abbreviation or acronym with an optional title attribute." },
  { question: "Which tag creates a dropdown option?", options: ["<dropdown>", "<option>", "<select>", "<input>"], correct: 1, difficulty: "easy", category: "HTML", explanation: "<option> defines an item within a <select> dropdown list." },
  { question: "What is the purpose of the <mark> tag?", options: ["Marks as deleted", "Highlights text", "Creates a bookmark", "Marks as important"], correct: 1, difficulty: "easy", category: "HTML", explanation: "<mark> represents text highlighted for reference or notation purposes." },
  { question: "Which attribute specifies the character encoding?", options: ["charset", "encoding", "char", "text-encoding"], correct: 0, difficulty: "easy", category: "HTML", explanation: "The charset attribute on <meta> specifies the character encoding for the document." },
  { question: "What does the <progress> tag display?", options: ["A loading spinner", "A progress bar", "A meter gauge", "A percentage text"], correct: 1, difficulty: "easy", category: "HTML", explanation: "<progress> displays the completion progress of a task as a progress bar." },
  { question: "Which tag groups related form elements?", options: ["<group>", "<fieldset>", "<form>", "<section>"], correct: 1, difficulty: "easy", category: "HTML", explanation: "<fieldset> groups related controls and labels in a form." },
  { question: "What does the <output> tag represent?", options: ["Console output", "The result of a calculation", "Error messages", "File output"], correct: 1, difficulty: "easy", category: "HTML", explanation: "<output> represents the result of a calculation or user action." },
  { question: "What is the purpose of the <datalist> tag?", options: ["Stores data locally", "Provides a list of predefined options for an input", "Creates a database", "Hides data"], correct: 1, difficulty: "medium", category: "HTML", explanation: "<datalist> contains a set of <option> elements representing acceptable values for an input." },
  { question: "What does the loading='lazy' attribute do on images?", options: ["Loads image immediately", "Defers loading until the image is near the viewport", "Preloads the image", "Compresses the image"], correct: 1, difficulty: "medium", category: "HTML", explanation: "loading='lazy' defers offscreen image loading until the user scrolls near them." },
  { question: "Which tag defines a key event?", options: ["<key>", "<kbd>", "<code>", "<input>"], correct: 1, difficulty: "medium", category: "HTML", explanation: "<kbd> represents keyboard input, typically rendered in monospace." },
  { question: "What is the srcset attribute?", options: ["Sets a source code", "Provides multiple image sources for different resolutions", "Sets a stylesheet", "Defines a script source"], correct: 1, difficulty: "medium", category: "HTML", explanation: "srcset lets you specify multiple image files for the browser to choose from based on screen size." },
  { question: "What does the <template> tag do?", options: ["Displays visible content", "Stores HTML fragments not rendered until activated via JS", "Creates a page layout", "Defines a header template"], correct: 1, difficulty: "medium", category: "HTML", explanation: "<template> holds content that is not rendered but can be instantiated at runtime." },
  { question: "What is the difference between <strong> and <b>?", options: ["No difference", "<strong> adds semantic importance, <b> is purely visual", "<b> is deprecated", "<strong> is deprecated"], correct: 1, difficulty: "medium", category: "HTML", explanation: "<strong> conveys semantic importance; <b> just makes text bold without added meaning." },
  { question: "What is the purpose of the <slot> tag?", options: ["Time slot", "Placeholder content in Web Components", "Form input slot", "Memory slot"], correct: 1, difficulty: "medium", category: "HTML", explanation: "<slot> in Web Components acts as a placeholder for external markup." },
  { question: "What does the defer attribute on scripts do?", options: ["Delays the script indefinitely", "Defers execution until after HTML parsing is complete", "Removes the script", "Compresses the script"], correct: 1, difficulty: "medium", category: "HTML", explanation: "defer ensures script execution happens after the document is fully parsed." },
  { question: "Which tag defines a media resource for <video> or <audio>?", options: ["<media>", "<source>", "<src>", "<ref>"], correct: 1, difficulty: "medium", category: "HTML", explanation: "<source> specifies multiple media resources for media elements." },
  { question: "What is the role attribute used for?", options: ["Defining CSS classes", "Specifying ARIA roles for accessibility", "Setting element ID", "Defining data attributes"], correct: 1, difficulty: "medium", category: "HTML", explanation: "role defines the type of element for assistive technologies (e.g., role='button')." },
  { question: "What does the <details> tag create?", options: ["A detail view page", "A collapsible content section", "A footnote", "A tooltip"], correct: 1, difficulty: "medium", category: "HTML", explanation: "<details> creates a disclosure widget that can be opened/closed, with <summary> as its label." },
  { question: "Which tag creates a figure caption?", options: ["<figcaption>", "<caption>", "<label>", "<span>"], correct: 0, difficulty: "medium", category: "HTML", explanation: "<figcaption> provides a caption for a <figure> element." },

  // ─── CSS (additional) ───────────────────────────
  { question: "What does display: none do?", options: ["Makes element invisible but takes space", "Removes element from document flow completely", "Hides element with opacity", "Moves element offscreen"], correct: 1, difficulty: "easy", category: "CSS", explanation: "display: none removes the element entirely from the document flow." },
  { question: "Which property sets the background color?", options: ["bgcolor", "background-color", "color-bg", "bg-color"], correct: 1, difficulty: "easy", category: "CSS", explanation: "background-color sets the background color of an element." },
  { question: "How do you make a list horizontal?", options: ["display: inline", "display: flex", "list-style: horizontal", "float: left"], correct: 1, difficulty: "easy", category: "CSS", explanation: "display: flex on the list container makes list items lay out horizontally." },
  { question: "What does font-family do?", options: ["Sets font weight", "Defines the typeface for text", "Sets font size", "Changes font color"], correct: 1, difficulty: "easy", category: "CSS", explanation: "font-family specifies the font(s) for an element." },
  { question: "Which property controls the space between lines of text?", options: ["letter-spacing", "word-spacing", "line-height", "text-spacing"], correct: 2, difficulty: "easy", category: "CSS", explanation: "line-height controls the distance between lines of text." },
  { question: "How do you hide overflow content?", options: ["overflow: hidden", "display: none", "visibility: hidden", "overflow: off"], correct: 0, difficulty: "easy", category: "CSS", explanation: "overflow: hidden clips content that overflows the element's box." },
  { question: "What does position: relative do?", options: ["Removes from flow", "Positions relative to its normal position", "Makes it a parent element", "Centers it"], correct: 1, difficulty: "easy", category: "CSS", explanation: "position: relative positions the element relative to where it would normally be placed." },
  { question: "Which property adds a shadow to an element?", options: ["text-shadow", "element-shadow", "box-shadow", "drop-shadow"], correct: 2, difficulty: "easy", category: "CSS", explanation: "box-shadow adds shadow effects around an element's frame." },
  { question: "What does overflow: auto do?", options: ["Hides overflow", "Adds scrollbars only when content overflows", "Expands the container", "Crops the content"], correct: 1, difficulty: "easy", category: "CSS", explanation: "overflow: auto adds scrollbars only when content exceeds the container." },
  { question: "Which property changes cursor appearance on hover?", options: ["pointer", "cursor", "hover-style", "mouse"], correct: 1, difficulty: "easy", category: "CSS", explanation: "The cursor property defines the mouse cursor type (e.g., pointer, text, crosshair)." },
  { question: "What does max-width do?", options: ["Sets exact width", "Limits the maximum width while allowing smaller sizes", "Forces full width", "Removes width constraints"], correct: 1, difficulty: "easy", category: "CSS", explanation: "max-width prevents an element from growing wider than the specified value." },
  { question: "Which unit is viewport-relative?", options: ["em", "rem", "vw", "px"], correct: 2, difficulty: "easy", category: "CSS", explanation: "vw (viewport width) is relative to 1% of the viewport's width." },
  { question: "What does text-align: center do?", options: ["Centers the element", "Centers inline content within a block", "Centers the container", "Centers background"], correct: 1, difficulty: "easy", category: "CSS", explanation: "text-align centers inline content (text, images) inside a block container." },
  { question: "What does the :hover pseudo-class do?", options: ["Styles during click", "Styles when the mouse is over the element", "Styles when focused", "Styles on load"], correct: 1, difficulty: "easy", category: "CSS", explanation: ":hover applies styles when the user's pointer is over an element." },
  { question: "Which property makes text uppercase?", options: ["text-transform: uppercase", "text-case: upper", "font-transform: capitalize", "text-style: uppercase"], correct: 0, difficulty: "easy", category: "CSS", explanation: "text-transform: uppercase converts all text to uppercase letters." },
  { question: "What does grid-template-columns define?", options: ["Number of rows", "Width of each grid column", "Grid gap", "Grid background"], correct: 1, difficulty: "medium", category: "CSS", explanation: "grid-template-columns defines the track sizes and number of columns in a CSS Grid." },
  { question: "What does position: sticky do?", options: ["Always fixed", "Toggles between relative and fixed based on scroll position", "Makes it float", "Sticks to other elements"], correct: 1, difficulty: "medium", category: "CSS", explanation: "sticky acts as relative until a scroll threshold, then becomes fixed." },
  { question: "What is the difference between visibility: hidden and display: none?", options: ["No difference", "hidden keeps space, none removes element from flow", "none keeps space", "hidden is faster"], correct: 1, difficulty: "medium", category: "CSS", explanation: "visibility: hidden hides the element but it still takes up space; display: none removes it entirely." },
  { question: "What does the * selector target?", options: ["Only the first element", "All elements", "The parent element", "No elements"], correct: 1, difficulty: "medium", category: "CSS", explanation: "The universal selector * targets every element in the document." },
  { question: "What does the :nth-child() pseudo-class do?", options: ["Selects the last child", "Selects elements based on their position among siblings", "Selects all children", "Selects the parent"], correct: 1, difficulty: "medium", category: "CSS", explanation: ":nth-child(n) selects elements that are the nth child of their parent." },
  { question: "What does aspect-ratio: 16/9 do?", options: ["Sets width to 16, height to 9", "Maintains a 16:9 width-to-height ratio", "Creates a 16x9 grid", "Sets font ratio"], correct: 1, difficulty: "medium", category: "CSS", explanation: "aspect-ratio sets a preferred ratio for the box, maintaining proportions when resizing." },
  { question: "What is the clip-path property?", options: ["Draws a border", "Defines a clipping region for an element", "Adds a background clip", "Hides the element"], correct: 1, difficulty: "medium", category: "CSS", explanation: "clip-path creates a clipping region that determines what part of an element is visible." },
  { question: "What does place-items: center do?", options: ["Centers text", "Centers items in both directions in Grid/Flex", "Centers the container", "Adds padding"], correct: 1, difficulty: "medium", category: "CSS", explanation: "place-items: center is shorthand for align-items and justify-items, centering items in both axes." },
  { question: "What does the 'inherit' keyword do?", options: ["Creates a copy", "Takes the value from the parent element", "Sets default value", "Removes the property"], correct: 1, difficulty: "medium", category: "CSS", explanation: "inherit forces the element to take its computed value from its parent element." },
  { question: "What does scroll-behavior: smooth do?", options: ["Smooths text", "Enables smooth scrolling when navigating to anchors", "Smooths animations", "Reduces scroll speed"], correct: 1, difficulty: "medium", category: "CSS", explanation: "scroll-behavior: smooth animates the scrolling when navigating to anchor links." },
  { question: "What is the difference between 'em' and 'rem'?", options: ["No difference", "em is relative to parent, rem is relative to root element", "rem is deprecated", "em is root-relative"], correct: 1, difficulty: "medium", category: "CSS", explanation: "em is relative to the parent element's font size; rem is relative to the root (html) element." },
  { question: "What does backdrop-filter do?", options: ["Filters the element itself", "Applies filter effects to the area behind an element", "Filters background images", "Creates a backdrop div"], correct: 1, difficulty: "medium", category: "CSS", explanation: "backdrop-filter applies CSS effects like blur to the area behind an element (e.g., glass morphism)." },
  { question: "What does object-fit: cover do?", options: ["Covers the entire page", "Scales image to cover the container while maintaining aspect ratio", "Stretches the image", "Hides overflow"], correct: 1, difficulty: "medium", category: "CSS", explanation: "object-fit: cover fills the container by scaling the image to maintain ratio, cropping if needed." },
  { question: "What does the 'initial' keyword do?", options: ["Sets value to empty", "Resets the property to its default value", "Initializes a variable", "Sets to first value"], correct: 1, difficulty: "medium", category: "CSS", explanation: "initial sets the property to its default (initial) value as defined in the CSS specification." },
  { question: "What does the CSS 'repeating-linear-gradient' do?", options: ["Creates a single gradient", "Creates a gradient pattern that repeats", "Animates a gradient", "Creates a radial pattern"], correct: 1, difficulty: "medium", category: "CSS", explanation: "repeating-linear-gradient creates a gradient that repeats the pattern to fill the space." },
  { question: "What does the @layer rule do?", options: ["Creates animation layers", "Manages cascade layers for controlling specificity", "Adds depth to elements", "Creates a stacking context"], correct: 1, difficulty: "hard", category: "CSS", explanation: "@layer defines cascade layers, giving explicit control over the order of CSS specificity." },
  { question: "What is the :is() pseudo-class?", options: ["Checks if element exists", "Matches any of the selectors in its argument list", "Checks element state", "Validates input"], correct: 1, difficulty: "hard", category: "CSS", explanation: ":is() takes a selector list and matches any element that can be selected by one of the selectors." },
  { question: "What does the color-mix() function do?", options: ["Mixes colors in an image", "Creates a new color by mixing two colors in a given color space", "Validates color codes", "Picks a random color"], correct: 1, difficulty: "hard", category: "CSS", explanation: "color-mix() interpolates between two colors in a specified color space." },
  { question: "What is container queries (@container)?", options: ["Queries the DOM", "Applies styles based on the size of a parent container instead of viewport", "Queries the browser", "Queries the server"], correct: 1, difficulty: "hard", category: "CSS", explanation: "Container queries let you style elements based on their container's size rather than the viewport." },
  { question: "What does :has() pseudo-class do?", options: ["Checks for child elements", "Selects elements that have matching descendants or siblings", "Has a specific attribute", "Has focus"], correct: 1, difficulty: "hard", category: "CSS", explanation: ":has() selects elements that contain a certain element matching the selector (the 'parent selector')." },
  { question: "What is CSS nesting?", options: ["Embedding styles in HTML", "Writing CSS rules inside other rules using &", "Nesting div elements", "Using z-index"], correct: 1, difficulty: "hard", category: "CSS", explanation: "CSS nesting allows writing selectors inside other selectors using the & combinator, similar to preprocessors." },
  { question: "What does light-dark() function do?", options: ["Changes text color", "Returns a light or dark value based on the user's color scheme preference", "Toggles theme", "Applies filters"], correct: 1, difficulty: "hard", category: "CSS", explanation: "light-dark() accepts two color values and returns the appropriate one based on the current color scheme." },
  { question: "What is the @scope rule?", options: ["Scopes JavaScript", "Defines a scope limit for CSS selectors to a subtree of the DOM", "Limits media queries", "Creates shadow DOM"], correct: 1, difficulty: "hard", category: "CSS", explanation: "@scope limits which elements a CSS rule applies to, targeting a specific DOM subtree." },
  { question: "What does the @starting-style rule do?", options: ["Defines initial styles for all elements", "Defines styles for elements entering the DOM for the first time", "Sets the first stylesheet", "Creates a style reset"], correct: 1, difficulty: "hard", category: "CSS", explanation: "@starting-style defines the initial state for CSS transitions when an element is first rendered." },
  { question: "What is the view-transitions API in CSS?", options: ["Camera transitions", "Enables smooth animated transitions between DOM states", "Page transitions only", "SVG animations"], correct: 1, difficulty: "hard", category: "CSS", explanation: "CSS view transitions animate between old and new states of the DOM during navigation or state changes." },
  { question: "What does the text-wrap: balance property do?", options: ["Balances font weights", "Balances line lengths for more even wrapping", "Aligns text center", "Justifies text"], correct: 1, difficulty: "hard", category: "CSS", explanation: "text-wrap: balance distributes text across lines so they are more equal in length." },

  // ─── React (additional) ─────────────────────────
  { question: "What is React Fragment?", options: ["A broken component", "A way to group elements without adding an extra DOM node", "An error boundary", "A type of portal"], correct: 1, difficulty: "easy", category: "React", explanation: "Fragment lets you group children without adding extra wrapper elements to the DOM." },
  { question: "What is JSX?", options: ["A new language", "JavaScript XML syntax extension", "A CSS framework", "A testing library"], correct: 1, difficulty: "easy", category: "React", explanation: "JSX is a syntax extension that lets you write HTML-like code inside JavaScript." },
  { question: "How do you pass data from parent to child in React?", options: ["Using state only", "Using props", "Using context only", "Using DOM"], correct: 1, difficulty: "easy", category: "React", explanation: "Props are the primary way to pass data from parent to child components." },
  { question: "What is the key difference between a class and functional component?", options: ["No difference", "Class components use this keyword, functional components use hooks", "Functional components are slower", "Class components are deprecated"], correct: 1, difficulty: "easy", category: "React", explanation: "Class components use 'this' state and lifecycle methods; functional components use hooks." },
  { question: "What does React.memo do?", options: ["Adds comments", "Prevents re-renders if props haven't changed", "Memoizes the DOM", "Creates a memo"], correct: 1, difficulty: "easy", category: "React", explanation: "React.memo skips re-rendering when props are shallowly equal." },
  { question: "What is the purpose of the key prop in lists?", options: ["Styling", "Helps React identify which items changed", "Sets the order", "Assigns IDs"], correct: 1, difficulty: "easy", category: "React", explanation: "Keys help React determine which items in a list have been added, removed, or changed." },
  { question: "How do you handle form input in React?", options: ["Directly modify the DOM", "Use controlled components with state", "Use jQuery", "Use innerHTML"], correct: 1, difficulty: "easy", category: "React", explanation: "Controlled components bind input values to React state, updating on every change." },
  { question: "What does the return statement do in a component?", options: ["Exports the component", "Specifies the JSX to render", "Returns data to parent", "Ends the component lifecycle"], correct: 1, difficulty: "easy", category: "React", explanation: "The return statement defines what JSX the component renders to the DOM." },
  { question: "What is the default behavior of useEffect on every render?", options: ["Nothing", "Runs the effect function after every render", "Skips the effect", "Only runs on mount"], correct: 1, difficulty: "easy", category: "React", explanation: "Without a dependency array, useEffect runs after every render." },
  { question: "What does React.StrictMode do?", options: ["Enforces strict typing", "Activates additional development warnings and checks", "Prevents all errors", "Disables console.log"], correct: 1, difficulty: "easy", category: "React", explanation: "StrictMode highlights potential problems and runs extra checks in development mode." },
  { question: "What is the purpose of useCallback?", options: ["Calls a function once", "Returns a memoized version of a callback function", "Creates a new function every render", "Handles async calls"], correct: 1, difficulty: "medium", category: "React", explanation: "useCallback returns a memoized callback that only changes when its dependencies change." },
  { question: "What is React.lazy used for?", options: ["Making components slow", "Code-splitting — loading components on demand", "Lazy loading images", "Delayed rendering"], correct: 1, difficulty: "medium", category: "React", explanation: "React.lazy dynamically imports a component, splitting it into a separate chunk." },
  { question: "What is the purpose of Suspense?", options: ["Catching errors", "Showing a fallback while waiting for async content (like lazy components)", "Pausing animations", "Suspending state updates"], correct: 1, difficulty: "medium", category: "React", explanation: "Suspense shows a fallback UI while waiting for lazy-loaded content or data to load." },
  { question: "What does useReducer return?", options: ["Just the state", "The state and a dispatch function", "A single value", "A Promise"], correct: 1, difficulty: "medium", category: "React", explanation: "useReducer returns the current state and a dispatch function to trigger actions." },
  { question: "What happens when you call setState?", options: ["Immediately updates the DOM", "Schedules a re-render with new state", "Resets the component", "Unmounts the component"], correct: 1, difficulty: "medium", category: "React", explanation: "setState schedules a re-render; React batches updates for performance." },
  { question: "What is the purpose of useRef?", options: ["Referencing CSS files", "Persisting values across renders without causing re-renders", "Creating references to DOM elements", "Both B and C"], correct: 3, difficulty: "medium", category: "React", explanation: "useRef returns a mutable ref object whose .current persists across renders without triggering re-render." },
  { question: "What is a controlled component?", options: ["A component managed by Redux", "An input whose value is controlled by React state", "A component with error handling", "A component using Context"], correct: 1, difficulty: "medium", category: "React", explanation: "Controlled components have their form data handled by React state, not the DOM." },
  { question: "What is an uncontrolled component?", options: ["A broken component", "An input that manages its own state internally via the DOM", "A component without props", "A component without state"], correct: 1, difficulty: "medium", category: "React", explanation: "Uncontrolled components store their state in the DOM, accessed via refs." },
  { question: "What does the children prop represent?", options: ["Parent component", "Nested JSX elements passed between opening and closing tags", "Sibling components", "The first child element only"], correct: 1, difficulty: "medium", category: "React", explanation: "children is a special prop containing any nested elements between a component's opening and closing tags." },
  { question: "What is the difference between state and props?", options: ["No difference", "State is mutable and internal, props are external and read-only", "Props are mutable", "State is global"], correct: 1, difficulty: "medium", category: "React", explanation: "State is managed within the component and can change; props are passed in and cannot be modified by the component." },
  { question: "What does shouldComponentUpdate do?", options: ["Forces an update", "Lets you control whether a component re-renders", "Prevents all updates", "Updates the DOM"], correct: 1, difficulty: "medium", category: "React", explanation: "shouldComponentUpdate returns a boolean that controls whether the component should re-render." },
  { question: "What is the purpose of error boundaries?", options: ["Catching runtime errors in child components", "Preventing all errors", "Handling async errors", "Catching CSS errors"], correct: 0, difficulty: "medium", category: "React", explanation: "Error boundaries catch JavaScript errors in their child component tree and display fallback UI." },
  { question: "What does the useLayoutEffect hook do?", options: ["Same as useEffect", "Runs synchronously after DOM mutations but before the browser paints", "Runs before DOM updates", "Measures layout only"], correct: 1, difficulty: "hard", category: "React", explanation: "useLayoutEffect fires synchronously after DOM mutations, blocking the browser from painting." },
  { question: "What is React Server Components?", options: ["Components that run on the server only and send rendered HTML to the client", "Components that require a server", "Components for WebSocket", "Server-side routing"], correct: 0, difficulty: "hard", category: "React", explanation: "RSCs render on the server, reducing client-side JavaScript and enabling direct database access." },
  { question: "What does the useId hook generate?", options: ["A random number", "A unique, stable ID for accessibility attributes", "A CSS class name", "A component key"], correct: 1, difficulty: "hard", category: "React", explanation: "useId generates a unique, stable identifier that works consistently between server and client rendering." },
  { question: "What is concurrent rendering in React?", options: ["Rendering multiple components at once", "A mode where React can prepare multiple versions of the UI simultaneously", "Parallel processing", "Multithreading"], correct: 1, difficulty: "hard", category: "React", explanation: "Concurrent mode lets React interrupt and resume rendering to keep the UI responsive." },
  { question: "What does useSyncExternalStore do?", options: ["Stores data locally", "Subscribes to external data sources with tear-free reads", "Saves state to server", "Syncs with localStorage"], correct: 1, difficulty: "hard", category: "React", explanation: "useSyncExternalStore safely subscribes to external stores, ensuring consistent reads during concurrent rendering." },
  { question: "What is the difference between useEffect and useLayoutEffect?", options: ["No difference", "useEffect runs asynchronously after paint, useLayoutEffect runs synchronously before paint", "useLayoutEffect is deprecated", "useEffect runs before paint"], correct: 1, difficulty: "hard", category: "React", explanation: "useEffect fires after the browser paints (async), useLayoutEffect fires before the browser paints (sync)." },
  { question: "What is the purpose of React.memo with areEqual?", options: ["Custom comparison function to determine if re-render is needed", "Deep equality check", "Type checking", "Performance monitoring"], correct: 0, difficulty: "hard", category: "React", explanation: "areEqual is an optional second argument to React.memo for custom shallow comparison logic." },
  { question: "What does the useImperativeHandle hook do?", options: ["Handles imperative DOM operations", "Customizes the ref value exposed to parent components", "Imperatively updates state", "Creates imperative methods"], correct: 1, difficulty: "hard", category: "React", explanation: "useImperativeHandle customizes the instance value that parent components receive when using ref." },
  { question: "What is the difference between useMemo and useCallback?", options: ["No difference", "useMemo caches a value, useCallback caches a function", "useMemo is faster", "useCallback caches a value"], correct: 1, difficulty: "hard", category: "React", explanation: "useMemo memoizes a computed value; useCallback memoizes a function definition." },
  { question: "What is concurrent features (useTransition)?", options: ["Adding CSS transitions", "Marking state updates as non-urgent to keep UI responsive", "Transitioning between pages", "Animating component mounting"], correct: 1, difficulty: "hard", category: "React", explanation: "useTransition marks state updates as low priority, allowing the UI to remain responsive." },
  { question: "What does useDeferredValue do?", options: ["Delays rendering indefinitely", "Returns a deferred version of a value that updates at lower priority", "Defers state initialization", "Creates a delayed effect"], correct: 1, difficulty: "hard", category: "React", explanation: "useDeferredValue returns a value that can lag behind the actual value, prioritizing more urgent updates." },
  { question: "What is the purpose of React.Profiler?", options: ["Profiling network requests", "Measures rendering performance of a component tree", "Debugging memory leaks", "Profiling CPU usage"], correct: 1, difficulty: "hard", category: "React", explanation: "React.Profiler measures how often a React application renders and the cost of each render." },

  // ─── Cybersecurity (additional) ─────────────────
  { question: "What is a brute force attack?", options: ["Using encryption", "Trying all possible passwords until the correct one is found", "Physical force", "Social engineering"], correct: 1, difficulty: "easy", category: "Cybersecurity", explanation: "A brute force attack systematically tries every possible combination until the correct one is found." },
  { question: "What does a VPN do?", options: ["Increases internet speed", "Encrypts your internet connection and hides your IP", "Blocks all ads", "Prevents malware"], correct: 1, difficulty: "easy", category: "Cybersecurity", explanation: "A VPN creates an encrypted tunnel between your device and the internet, masking your IP address." },
  { question: "What is malware?", options: ["Good software", "Software designed to harm or exploit systems", "A type of hardware", "An operating system"], correct: 1, difficulty: "easy", category: "Cybersecurity", explanation: "Malware (malicious software) includes viruses, worms, trojans, and ransomware designed to damage systems." },
  { question: "What is social engineering?", options: ["Building social networks", "Manipulating people into revealing confidential information", "Social media marketing", "Engineering social apps"], correct: 1, difficulty: "easy", category: "Cybersecurity", explanation: "Social engineering exploits human psychology to trick people into giving up sensitive information." },
  { question: "What is a strong password example?", options: ["123456", "password", "P@ssw0rd!2024", "qwerty"], correct: 2, difficulty: "easy", category: "Cybersecurity", explanation: "Strong passwords combine uppercase, lowercase, numbers, and symbols with sufficient length." },
  { question: "What does encryption do?", options: ["Deletes data", "Converts data into a coded format to prevent unauthorized access", "Compresses data", "Backs up data"], correct: 1, difficulty: "easy", category: "Cybersecurity", explanation: "Encryption transforms readable data into ciphertext that can only be read with the correct decryption key." },
  { question: "What is the purpose of antivirus software?", options: ["Speeds up your computer", "Detects and removes malicious software", "Manages files", "Optimizes network"], correct: 1, difficulty: "easy", category: "Cybersecurity", explanation: "Antivirus software identifies, prevents, and removes malicious software from your system." },
  { question: "What is a password manager?", options: ["A person who manages passwords", "Software that securely stores and generates passwords", "A password reset tool", "A website login page"], correct: 1, difficulty: "easy", category: "Cybersecurity", explanation: "Password managers securely store all your passwords in an encrypted vault, accessible with one master password." },
  { question: "What is the danger of public Wi-Fi?", options: ["Slower speeds", "Attackers can intercept unencrypted data on the same network", "More ads", "IP bans"], correct: 1, difficulty: "easy", category: "Cybersecurity", explanation: "Public Wi-Fi is unencrypted, making it easy for attackers to intercept your data through man-in-the-middle attacks." },
  { question: "What is ransomware?", options: ["Software that asks for ransom payments", "Malware that encrypts files and demands payment for the decryption key", "A type of spyware", "Adware"], correct: 1, difficulty: "easy", category: "Cybersecurity", explanation: "Ransomware encrypts a victim's files and demands payment (usually cryptocurrency) for the decryption key." },
  { question: "What is the purpose of a VPN kill switch?", options: ["Turns off the VPN", "Blocks all internet traffic if the VPN connection drops", "Speeds up VPN", "Changes VPN server"], correct: 1, difficulty: "easy", category: "Cybersecurity", explanation: "A kill switch immediately cuts internet access if the VPN connection is lost, preventing data leaks." },
  { question: "What is a DDoS attack?", options: ["A direct data attack", "Distributed Denial of Service — overwhelming a server with traffic from multiple sources", "A physical attack", "Data deletion attack"], correct: 1, difficulty: "easy", category: "Cybersecurity", explanation: "DDoS floods a target server with massive traffic from many sources, causing service disruption." },
  { question: "What does HTTPS mean?", options: ["Hyper Text Transfer Protocol Secure", "High Tech Protocol", "Home Transfer Security", "Hyper Terminal Protocol"], correct: 0, difficulty: "easy", category: "Cybersecurity", explanation: "HTTPS is the secure version of HTTP, encrypting data between the browser and server using TLS/SSL." },
  { question: "What is a keylogger?", options: ["A keyboard shortcut", "Software that secretly records keystrokes", "A key management tool", "An encryption method"], correct: 1, difficulty: "easy", category: "Cybersecurity", explanation: "Keyloggers capture every keystroke, recording passwords and sensitive information without consent." },
  { question: "What is the principle of defense in depth?", options: ["One strong firewall", "Multiple layers of security controls throughout the system", "Deep code analysis", "Heavy encryption only"], correct: 1, difficulty: "easy", category: "Cybersecurity", explanation: "Defense in depth uses multiple overlapping security layers so if one fails, others still protect the system." },
  { question: "What is the purpose of a honeypot?", options: ["Storing passwords", "A decoy system designed to attract and detect attackers", "A sweetener for phishing", "A backup server"], correct: 1, difficulty: "medium", category: "Cybersecurity", explanation: "A honeypot is a decoy system that lures attackers, allowing security teams to study and deflect threats." },
  { question: "What is SQL injection prevention?", options: ["Using strong passwords only", "Using parameterized queries/prepared statements", "Escaping all HTML", "Using HTTPS only"], correct: 1, difficulty: "medium", category: "Cybersecurity", explanation: "Parameterized queries ensure user input is treated as data, not executable SQL code." },
  { question: "What does Content Security Policy (CSP) do?", options: ["Encrypts content", "Restricts which resources can load on a page to prevent XSS", "Compresses content", "Caches content"], correct: 1, difficulty: "medium", category: "Cybersecurity", explanation: "CSP defines rules for which resources (scripts, styles, images) a page is allowed to load." },
  { question: "What is a security audit?", options: ["A physical security check", "A systematic evaluation of an organization's security posture", "A code review", "A penetration test only"], correct: 1, difficulty: "medium", category: "Cybersecurity", explanation: "A security audit comprehensively reviews policies, procedures, and controls to identify vulnerabilities." },
  { question: "What is role-based access control (RBAC)?", options: ["Everyone gets admin access", "Permissions are assigned based on user roles within an organization", "No access control", "Password-based access"], correct: 1, difficulty: "medium", category: "Cybersecurity", explanation: "RBAC restricts system access based on a user's role, following least-privilege principles." },
  { question: "What is an SSL/TLS certificate?", options: ["A physical certificate", "A digital certificate that authenticates a website's identity and enables encrypted connections", "An encryption algorithm", "A firewall rule"], correct: 1, difficulty: "medium", category: "Cybersecurity", explanation: "SSL/TLS certificates verify a website's identity and enable HTTPS encryption for secure communications." },
  { question: "What is the purpose of penetration testing?", options: ["Testing physical locks", "Simulating attacks to find security vulnerabilities before real attackers do", "Testing network speed", "Checking code syntax"], correct: 1, difficulty: "medium", category: "Cybersecurity", explanation: "Penetration testing (pen testing) simulates real attacks to identify and fix security weaknesses." },
  { question: "What is the risk of using the same password everywhere?", options: ["No risk", "One breach exposes all accounts using that password", "Faster login", "Easier to remember"], correct: 1, difficulty: "medium", category: "Cybersecurity", explanation: "Credential stuffing attacks use leaked passwords from one breach to access other accounts." },
  { question: "What is the purpose of security headers?", options: ["Making pages look secure", "Adding HTTP headers that protect against common web attacks", "Encrypting headers only", "Speeding up requests"], correct: 1, difficulty: "medium", category: "Cybersecurity", explanation: "Security headers like X-Content-Type-Options and X-Frame-Options protect against various attacks." },
  { question: "What is a buffer overflow attack?", options: ["Adding too much data to a buffer causing it to overwrite adjacent memory", "Filling a database", "Buffering a video", "Adding extra data to a packet"], correct: 0, difficulty: "medium", category: "Cybersecurity", explanation: "Buffer overflow exploits write data beyond buffer boundaries, potentially executing arbitrary code." },
  { question: "What is the purpose of an intrusion detection system (IDS)?", options: ["Preventing all attacks", "Monitoring network traffic for suspicious activity and alerting administrators", "Blocking all traffic", "Encrypting data"], correct: 1, difficulty: "medium", category: "Cybersecurity", explanation: "IDS monitors network traffic, identifies suspicious patterns, and alerts security teams." },
  { question: "What is the difference between symmetric and asymmetric encryption?", options: ["No difference", "Symmetric uses one key, asymmetric uses a public-private key pair", "Asymmetric is slower", "Symmetric uses two keys"], correct: 1, difficulty: "medium", category: "Cybersecurity", explanation: "Symmetric encryption uses a single shared key; asymmetric uses a public key to encrypt and a private key to decrypt." },
  { question: "What is DNS spoofing?", options: ["Changing DNS settings", "Redirecting DNS queries to malicious IP addresses by corrupting DNS cache", "Using a VPN", "Encrypting DNS"], correct: 1, difficulty: "medium", category: "Cybersecurity", explanation: "DNS spoofing corrupts DNS cache to redirect users to malicious websites instead of legitimate ones." },
  { question: "What is the purpose of MFA (Multi-Factor Authentication)?", options: ["Using multiple passwords", "Requiring two or more verification methods for account access", "Multiple user accounts", "Multiple browsers"], correct: 1, difficulty: "medium", category: "Cybersecurity", explanation: "MFA adds layers of security by requiring more than just a password (e.g., code + biometrics)." },
  { question: "What is a side-channel attack?", options: ["Attacking the channel provider", "Extracting information from physical implementation rather than the algorithm itself", "Attacking via a side menu", "Side-loading apps"], correct: 1, difficulty: "medium", category: "Cybersecurity", explanation: "Side-channel attacks exploit information like timing, power consumption, or electromagnetic leaks." },
  { question: "What is the purpose of a SIEM system?", options: ["Encrypting emails", "Aggregating and analyzing security logs for threat detection", "Managing firewalls only", "Password management"], correct: 1, difficulty: "medium", category: "Cybersecurity", explanation: "SIEM (Security Information and Event Management) collects, analyzes, and correlates security data in real time." },
  { question: "What is the risk of HTTP without TLS?", options: ["Faster loading", "Data transmitted in plaintext, easily intercepted by attackers", "Better SEO", "No risks"], correct: 1, difficulty: "medium", category: "Cybersecurity", explanation: "HTTP without TLS sends data unencrypted, making it vulnerable to eavesdropping and tampering." },
  { question: "What is a zero-day vulnerability?", options: ["A bug found on day zero of release", "A security flaw unknown to the vendor, with no patch available", "A vulnerability in test environments", "A bug that only exists for one day"], correct: 1, difficulty: "hard", category: "Cybersecurity", explanation: "Zero-day vulnerabilities are unknown to the software vendor and have no available fix." },
  { question: "What is the risk of side-channel timing attacks?", options: ["Network delay", "Measuring response times to infer sensitive information like encryption keys", "CPU overheating", "DNS delays"], correct: 1, difficulty: "hard", category: "Cybersecurity", explanation: "Timing attacks measure how long operations take to deduce secret information like cryptographic keys." },
  { question: "What is the purpose of a WAF (Web Application Firewall)?", options: ["Blocking all traffic", "Filtering and monitoring HTTP traffic between a web application and the internet", "Encrypting all traffic", "Caching content"], correct: 1, difficulty: "hard", category: "Cybersecurity", explanation: "A WAF protects web applications by filtering, monitoring, and blocking malicious HTTP traffic." },
  { question: "What is cross-site request forgery (CSRF) and how is it prevented?", options: ["SQL injection variant, prevented by parameterized queries", "Tricking users into making unintended requests, prevented by anti-CSRF tokens", "XSS variant, prevented by CSP", "Brute force, prevented by rate limiting"], correct: 1, difficulty: "hard", category: "Cybersecurity", explanation: "CSRF exploits authenticated sessions; anti-CSRF tokens ensure requests are intentionally initiated." },
  { question: "What is the difference between hashing and encryption?", options: ["No difference", "Hashing is one-way and irreversible, encryption is two-way and reversible", "Hashing is faster", "Encryption is one-way"], correct: 1, difficulty: "hard", category: "Cybersecurity", explanation: "Hashing converts data to a fixed-size fingerprint (irreversible); encryption can be reversed with the correct key." },
  { question: "What is the risk of a supply chain attack?", options: ["Physical supply theft", "Compromising a trusted software update or dependency to distribute malware", "Overloading servers", "SQL injection"], correct: 1, difficulty: "hard", category: "Cybersecurity", explanation: "Supply chain attacks target trusted software providers to distribute malware through legitimate updates." },
  { question: "What is memory-safe programming?", options: ["Using any language", "Languages/techniques that prevent memory corruption vulnerabilities like buffer overflows", "Using memory cards", "Memory optimization only"], correct: 1, difficulty: "hard", category: "Cybersecurity", explanation: "Memory-safe languages (Rust, Go) prevent common vulnerabilities like buffer overflows and use-after-free." },
  { question: "What is the principle of least privilege in cloud security?", options: ["Using free tier only", "Granting only the minimum permissions needed for each service or user", "Maximum permissions for all", "No permissions at all"], correct: 1, difficulty: "hard", category: "Cybersecurity", explanation: "Least privilege in cloud means every identity and service gets only the access required — nothing more." },
  { question: "What is API rate limiting and why is it a security measure?", options: ["Speed limit for APIs", "Restricting the number of API requests to prevent abuse, DoS, and brute force attacks", "Increasing API speed", "Caching API responses"], correct: 1, difficulty: "hard", category: "Cybersecurity", explanation: "Rate limiting throttles excessive requests, protecting against brute force, scraping, and denial-of-service attacks." },
  { question: "What is a passkey?", options: ["A physical key", "A FIDO2-based passwordless authentication method using public key cryptography", "A recovery code", "A type of cookie"], correct: 1, difficulty: "hard", category: "Cybersecurity", explanation: "Passkeys use FIDO2/WebAuthn to provide passwordless, phishing-resistant authentication via public-key cryptography." },
  { question: "What is the risk of a man-in-the-browser attack?", options: ["Browser crashes", "Malware that intercepts and manipulates browser communications in real-time", "Slow browsing", "Ad injection only"], correct: 1, difficulty: "hard", category: "Cybersecurity", explanation: "Man-in-the-browser malware compromises the browser itself, modifying transactions and intercepting data." },
  { question: "What is the purpose of certificate pinning?", options: ["Pinning certificates physically", "Binding a specific SSL/TLS certificate to a known public key to prevent MITM attacks", "Encrypting certificates", "Storing certificates in cookies"], correct: 1, difficulty: "hard", category: "Cybersecurity", explanation: "Certificate pinning ensures the app only trusts a specific certificate or public key, blocking forged certificates." },
];

function App() {
  React.useEffect(() => {
    const seedQuestions = async () => {
      const querySnapshot = await getDocs(collection(db, "questions"));
      const existingTexts = new Set(querySnapshot.docs.map(doc => doc.data().question));
      const missing = INITIAL_QUESTIONS.filter(q => !existingTexts.has(q.question));
      for (const q of missing) {
        await addDoc(collection(db, "questions"), q);
      }
    };
    seedQuestions();
  }, []);

  return (
    <AuthProvider>
      <ToastContainer theme="dark" position="top-right" />
      <Routes>
        {/* Public Routes */}
        <Route path="/" element={<LandingPage />} />
        <Route path="/login" element={<LoginPage />} />
        <Route path="/register" element={<RegisterPage />} />
        <Route path="/forgot-password" element={<ForgotPassword />} />

        {/* Student Routes */}
        <Route 
          path="/dashboard" 
          element={
            <ProtectedRoute>
              <Dashboard />
            </ProtectedRoute>
          } 
        />
        <Route 
          path="/quiz" 
          element={<ProtectedRoute><QuizPage /></ProtectedRoute>} 
        />
        <Route 
          path="/profile" 
          element={<ProtectedRoute><Profile /></ProtectedRoute>} 
        />
        <Route 
          path="/leaderboard" 
          element={<ProtectedRoute><Leaderboard /></ProtectedRoute>} 
        />
        <Route 
          path="/codelab" 
          element={<ProtectedRoute><CodeLab /></ProtectedRoute>} 
        />
        <Route 
          path="/ai-assistant" 
          element={<ProtectedRoute><AIAssistant /></ProtectedRoute>} 
        />
        <Route 
          path="/theory" 
          element={<ProtectedRoute><TheoryVault /></ProtectedRoute>} 
        />
        <Route 
          path="/cybersecurity" 
          element={<ProtectedRoute><Cybersecurity /></ProtectedRoute>} 
        />
        <Route 
          path="/analytics" 
          element={<ProtectedRoute><Analytics /></ProtectedRoute>} 
        />

        {/* Admin Routes (Strictly Protected) */}
        <Route 
          path="/admin/dashboard" 
          element={
            <ProtectedRoute requireAdmin={true}>
              <SuperAdminDashboard />
            </ProtectedRoute>
          } 
        />
        <Route 
          path="/admin/users" 
          element={
            <ProtectedRoute requireAdmin={true}>
              <UserManagement />
            </ProtectedRoute>
          } 
        />
        <Route 
          path="/admin/questions" 
          element={
            <ProtectedRoute requireAdmin={true}>
              <AdminPanel />
            </ProtectedRoute>
          } 
        />

        {/* Catch-all Redirect */}
        <Route path="/admin" element={<Navigate to="/admin/dashboard" replace />} />
      </Routes>
    </AuthProvider>
  );
}

export default App;
